### ISSUE TITLE
[PATCH] Fix testsuite for sqlite 3.10 compatibility.

### ISSUE THREAD

**Issue by gregoa** [sixapart/data-objectdriver#21]
In Debian we are currently applying the following patch to
Data-ObjectDriver.
We thought you might be interested in it too.

    Description: Fix testsuite for sqlite 3.10 compatibility.
     3.10 > 3.5 fails, so let's use version.pm;
     there might be more elegant options ...
    Origin: vendor
    Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810710
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-01-13
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdata-objectdriver-perl.git/plain/debian/patches/test-sqlite-3.10.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by ziguzagu** [comment]
@gregoa Thanks! We are going to release 0.14 including that patch soon.

**Comment by ziguzagu** [comment]
@gregoa I'v released 0.14:
https://metacpan.org/release/SIXAPART/Data-ObjectDriver-0.14

Thank you!

**Comment by gregoa** [comment]
On Wed, 13 Jan 2016 19:12:26 -0800, Hiroshi Sakai wrote:

> @gregoa I'v released 0.14:
> https://metacpan.org/release/SIXAPART/Data-ObjectDriver-0.14
> 
> Thank you!

Thanks to you!

Uploaded to Debian/unstable.


Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Bettina Wegner: es ist vorbei
