### ISSUE TITLE
Inconsistent License terms

### ISSUE THREAD

**Issue by kentfredric** [sixapart/data-objectdriver#34]
Top level files like LICENSE and META.* indicate "Artistic-2", while the .pm files all seem to say "perl itself" for their license, where "perl itself" means "Artistic-1" OR "GPL1-OR-Newer".

If I had to guess, I'd say the metadata is wrong, and should be updated to reflect the .pm files.

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/minil.toml#L3

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/LICENSE#L3-L7

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/META.json#L8-L10

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/BaseObject.pm#L1286-L1290

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/Errors.pm#L45-L48

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/SQL/Oracle.pm#L51-L56

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/Driver/BaseCache.pm#L440-L444

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/Driver/DBD/Oracle.pm#L147-L151

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/Driver/DBD.pm#L192-L196

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/Driver/Partition.pm#L256-L259

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/Driver/SimplePartition.pm#L250-L254

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/Driver/Cache/Memcached.pm#L143-L147

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/Driver/Cache/Apache.pm#L168-L171

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver/SQL.pm#L678-L682

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/lib/Data/ObjectDriver.pm#L778-L781

https://github.com/sixapart/data-objectdriver/blob/b2f89425df33149fad0e5e9cc81bd1eaa87a17ec/README.md#L591-L595

**Comment by comewalk** [comment]
@kentfredric Thank you for creating this issue. This fixed at #35. The module will be available on CPAN as 0.20.
