### ISSUE TITLE
tests now fail in Data-ObjectDriver-0.19

### ISSUE THREAD

**Issue by eseyman** [sixapart/data-objectdriver#36]
Data-ObjectDriver-0.19 is packaged in Fedora (the package name is perl-Data-ObjectDriver) but tests now fail in the development tree. A perl-DBD-SQLite upgrade from 1.64-6.fc33 to 1.66-1.fc34 may be what caused the issue.

    t/12-windows.t ............. ok
    #   Failed test at t/20-driver-sqlite.t line 46.
    #          got: '0'
    #     expected: '1'
    Can't call method "rating" on an undefined value at t/20-driver-sqlite.t line 47.
    # Looks like your test exited with 2 just after 5.
    t/20-driver-sqlite.t ....... 
    Dubious, test returned 2 (wstat 512, 0x200)
    Failed 9/13 subtests

**Comment by charsbar** [comment]
@eseyman Thanks for reporting this. It surely is due to a change in DBD::SQLite 1.66 (actually 1.65_01), and we are discussing what to do with https://github.com/sixapart/data-objectdriver/blob/master/lib/Data/ObjectDriver/Driver/DBD/SQLite.pm#L23-L25 , (just to remove, or to modify).

**Comment by comewalk** [comment]
@eseyman Fixed by #37 and merged to master. Also new version as 0.20 is available on CPAN. Thanks!
